//1 get generateClientToken

GET https://dev.aistudios.com/api/odin/generateClientToken?appId=aistudios.com&userKey=6443234b-77d5-4013-bfd6-bb9399f317d9

{
  "succeed": true,
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6ImFpc3R1ZGlvcy5jb20iLCJwbGF0Zm9ybSI6IndlYiIsImlhdCI6MTY0MzAyMTE3NiwiZXhwIjoxNjQzMDIxNDc2fQ.adihls37rKlHTmaiIFHNxWCv6cx4BJp0YSaaCcKhXzo",
  "appId": "aistudios.com",
  "platform": "web",
  "tokenExpire": 1642962538
}

###

//2 post generateToken

POST https://dev.aistudios.com/api/odin/generateToken

{"appId":"aistudios.com","platform":"web","isClientToken":true,"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6ImFpc3R1ZGlvcy5jb20iLCJwbGF0Zm9ybSI6IndlYiIsImlhdCI6MTY0MzAyMTIxNiwiZXhwIjoxNjQzMDIxNTE2fQ._En7I1FwdkknxZs2XnJ8FtfuB2X00RAnUeabTBoNbAc","uuid":"6443234b-77d5-4013-bfd6-bb9399f317d9","sdk_v":"1.0","clientHostname":"aistudios.com","key":"-Mu7Dyb4qObdiQJZFfSP"}

###

//3 post makevideo
POST https://dev.aistudios.com/api/odin/makeVideo

{
"language":"ko",
"text":"유우우우우야아호오오오",
"model":"ysy",
"clothes":"2",
"appId":"aistudios.com",
"platform":"web",
"isClientToken":true,
"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6I…TkyfQ.xWFXpXNgug2R_58BlVRVBTL90pkwooA9SIZY7KSdSgk",
"uuid":"6443234b-77d5-4013-bfd6-bb9399f317d9",
"sdk_v":"1.0",
"clientHostname":"aistudios.com"
}

###

//4 find projcet
POST https://dev.aistudios.com/api/odin/findProject

{
    "appId":"aistudios.com",
    "platform":"web",
    "isClientToken":true,
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6ImFpc3R1ZGlvcy5jb20iLCJwbGF0Zm9ybSI6IndlYiIsImlhdCI6MTY0Mjg5OTQ0MCwiZXhwIjoxNjQyOTg1ODQwfQ.Fqj2FWR9zZFBPTlYxcJcfr_syaTmttR_jLy7XrU3QL8",
    "uuid":"6443234b-77d5-4013-bfd6-bb9399f317d9",
    "sdk_v":"1.0",
    "clientHostname":"aistudios.com",
}

###

post https://localhost:8000/user